# Form implementation generated from reading ui file 'd:\Python_PORTFOLIO\12_basic_currency_converter\App_main\UI\converter.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fm_main(object):
    def setupUi(self, fm_main):
        fm_main.setObjectName("fm_main")
        fm_main.resize(465, 500)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        fm_main.setFont(font)
        self.le_value_to_convert = QtWidgets.QLineEdit(parent=fm_main)
        self.le_value_to_convert.setGeometry(QtCore.QRect(180, 79, 261, 31))
        self.le_value_to_convert.setObjectName("le_value_to_convert")
        self.lb_value_to_convert = QtWidgets.QLabel(parent=fm_main)
        self.lb_value_to_convert.setGeometry(QtCore.QRect(30, 90, 131, 16))
        self.lb_value_to_convert.setObjectName("lb_value_to_convert")
        self.lb_from = QtWidgets.QLabel(parent=fm_main)
        self.lb_from.setGeometry(QtCore.QRect(20, 150, 47, 13))
        self.lb_from.setObjectName("lb_from")
        self.lb_to = QtWidgets.QLabel(parent=fm_main)
        self.lb_to.setGeometry(QtCore.QRect(20, 240, 31, 21))
        self.lb_to.setObjectName("lb_to")
        self.lcd_val_to = QtWidgets.QLCDNumber(parent=fm_main)
        self.lcd_val_to.setGeometry(QtCore.QRect(150, 290, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lcd_val_to.setFont(font)
        self.lcd_val_to.setDigitCount(12)
        self.lcd_val_to.setObjectName("lcd_val_to")
        self.cbb_from = QtWidgets.QComboBox(parent=fm_main)
        self.cbb_from.setGeometry(QtCore.QRect(150, 140, 291, 31))
        self.cbb_from.setObjectName("cbb_from")
        self.cbb_to = QtWidgets.QComboBox(parent=fm_main)
        self.cbb_to.setGeometry(QtCore.QRect(150, 230, 291, 31))
        self.cbb_to.setObjectName("cbb_to")
        self.pb_cancel = QtWidgets.QPushButton(parent=fm_main)
        self.pb_cancel.setGeometry(QtCore.QRect(350, 390, 91, 31))
        self.pb_cancel.setObjectName("pb_cancel")
        self.pb_swap = QtWidgets.QPushButton(parent=fm_main)
        self.pb_swap.setGeometry(QtCore.QRect(130, 390, 91, 31))
        self.pb_swap.setObjectName("pb_swap")
        self.pb_calculate = QtWidgets.QPushButton(parent=fm_main)
        self.pb_calculate.setGeometry(QtCore.QRect(240, 390, 91, 31))
        self.pb_calculate.setObjectName("pb_calculate")
        self.lb_message = QtWidgets.QLabel(parent=fm_main)
        self.lb_message.setGeometry(QtCore.QRect(30, 440, 441, 31))
        self.lb_message.setObjectName("lb_message")
        self.lb_date = QtWidgets.QLabel(parent=fm_main)
        self.lb_date.setGeometry(QtCore.QRect(30, 30, 251, 21))
        self.lb_date.setObjectName("lb_date")
        self.lb_short_from = QtWidgets.QLabel(parent=fm_main)
        self.lb_short_from.setGeometry(QtCore.QRect(70, 120, 71, 71))
        self.lb_short_from.setPixmap(QtGui.QPixmap(":/flags/empty.png"))
        self.lb_short_from.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_short_from.setObjectName("lb_short_from")
        self.lb_short_to = QtWidgets.QLabel(parent=fm_main)
        self.lb_short_to.setGeometry(QtCore.QRect(70, 210, 71, 71))
        self.lb_short_to.setPixmap(QtGui.QPixmap(":/flags/empty.png"))
        self.lb_short_to.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_short_to.setObjectName("lb_short_to")
        self.pb_reset = QtWidgets.QPushButton(parent=fm_main)
        self.pb_reset.setGeometry(QtCore.QRect(20, 390, 91, 31))
        self.pb_reset.setObjectName("pb_reset")

        self.retranslateUi(fm_main)
        QtCore.QMetaObject.connectSlotsByName(fm_main)

    def retranslateUi(self, fm_main):
        _translate = QtCore.QCoreApplication.translate
        fm_main.setWindowTitle(_translate("fm_main", "Currency converter"))
        self.lb_value_to_convert.setText(_translate("fm_main", "Value to convert:"))
        self.lb_from.setText(_translate("fm_main", "From:"))
        self.lb_to.setText(_translate("fm_main", "To:"))
        self.pb_cancel.setText(_translate("fm_main", "Cancel"))
        self.pb_swap.setText(_translate("fm_main", "Swap"))
        self.pb_calculate.setText(_translate("fm_main", "Calculate"))
        self.lb_date.setText(_translate("fm_main", "Date"))
        self.pb_reset.setText(_translate("fm_main", "Reset"))
